version: "3.8"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./stayease.db:/app/stayease.db
      - ./chroma_db:/app/chroma_db
      - ./uploads:/app/uploads
    env_file:
      - .env # This will load GROQ_API_KEY
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - api

  admin-frontend:
    build: ./admin-frontend
    ports:
      - "3001:80"
    restart: unless-stopped
    depends_on:
      - api
